### ISSUE TITLE
pipenv --three generates an error on Mac OS X

### ISSUE THREAD

**Issue by brunokrebs** [kennethreitz/pipenv#538]
I had to manually set the `python` variable to the correct place in the `cli.py` file because it was, somehow, getting the wrong path.

`which('python')` was returning `/bin/python/` instead of the correct path.

This is the stack trace:

```bash
Virtualenv location:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/cli.py", line 1163, in cli
    ensure_project(three=three, python=python)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/cli.py", line 382, in ensure_project
    if project.required_python_version not in python_version(path_to_python):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by brunokrebs** [comment]
I had to replace a bunch of lines that were using `python = which("python")` by `python = "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3"` to make it work. And also, I made similar changes to `which("pip")`. Of course, not the solution for this problem, but at least made it work around here.

**Comment by kennethreitz** [comment]
which python was it finding? 

Also, which version are you using?

**Comment by kennethreitz** [comment]
Closing this as cannot reproduce

**Comment by codefo** [comment]
@kennethreitz please reopen this bug, because I see the same error on my terminal.

<img width="682" alt="screen shot 2017-09-15 at 04 54 35" src="https://user-images.githubusercontent.com/59687/30463001-fcc2e6a0-99d1-11e7-97ae-51c0c180403e.png">

I use Python 3.6.2 it was installed by Homebrew and my `pipenv` was installed by `pip3`

**Comment by kennethreitz** [comment]
@codefo please show what command you were running to get this traceback.

**Comment by codefo** [comment]
@kennethreitz just `pipenv --three`

**Comment by brunokrebs** [comment]
Same scenario here. Would installing pipenv with `python` instead of `python3` be a workaround? Actually I don't think so, because as far as I understood `which('python')` is hard coded and returns and odd result: `/bin/python`.

I will take a further look into this issue during the weekend.

**Comment by kennethreitz** [comment]
we should have this fixed within a few hours, here. this is a pretty major issue.

**Comment by kennethreitz** [comment]
In the meantime do try `--python /full/path/to/python3` and let me know the results.

**Comment by kennethreitz** [comment]
and for the record, this is working fine on my machine, brew-installed.

**Comment by kennethreitz** [comment]
I think this is now fixed.

**Comment by kennethreitz** [comment]
if not, let's get a failing test written.

**Comment by kennethreitz** [comment]
<img width="657" alt="screen shot 2017-09-15 at 1 25 53 pm" src="https://user-images.githubusercontent.com/119893/30495288-7440f91e-9a19-11e7-98be-2c1d0e7749b5.png">

**Comment by kennethreitz** [comment]
please comment if this is still an issue for you on latest.

**Comment by brunokrebs** [comment]
@kennethreitz, I can confirm that the bug is really gone. Thank you very much for your effort. Great job! 😄

**Comment by kennethreitz** [comment]
excellent news!

**Comment by jussihuotari** [comment]
Not working for me on MacOs + Brew-installed python3. However, the error went away after setting the locale so I assume this may have something to do with https://bugs.python.org/issue18378.

```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```


Before the above mentioned exports:

```
$ which pip3
/usr/local/bin/pip3
$ pip3 install pipenv
Collecting pipenv
  ...
  ...
  ...
Successfully installed pipenv-7.3.7
$ pipenv --three
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project…
Using /usr/local/bin/python3 to create virtualenv…
...
...
Virtualenv location: 
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1422, in cli
    ensure_project(three=three, python=python, warn=True)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 549, in ensure_project
    ensure_pipfile(validate=validate)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 293, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 328, in create_pipfile
    data[u'requires'] = {'python_version': python_version(python)[:len('2.7')]}
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kennethreitz** [comment]
Yeah 

```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
are required.

**Comment by offby1** [comment]
I'm having more or less the same problem.  I've attached what I hope is enough information to reproduce it.
[bug-report.txt](https://github.com/kennethreitz/pipenv/files/1346819/bug-report.txt)

**Comment by kennethreitz** [comment]
@offby1 upgrade your setuptools

**Comment by jschulenklopper** [comment]
Had a similar error when `pipenv install requests`, 

> Error:  An error occurred while installing requests!
> /bin/sh: /bin/pip: No such file or directory

but setting `LANG` _and_ `LC_ALL` did solve the problem.

**Comment by hyperknot** [comment]
I can reproduce this bug, it depends on the Language & Region System preferences.

Good:
1. Set Language & Region to something non-English first.
![image](https://user-images.githubusercontent.com/494223/32606971-8ba4b0c8-c557-11e7-8881-66aba48278bb.png)
2. $HOME/.CFUserTextEncoding file contains something like `0x1D:0x2B`
3. pipenv works perfectly

Bad:
1. Set Language & Region to English first.
![image](https://user-images.githubusercontent.com/494223/32606999-b224c076-c557-11e7-8293-abf1ff4a6abe.png)
2. $HOME/.CFUserTextEncoding file contains something like `0x0:0x0`
3. Pipenv terminates with the following traceback:

pipenv shell
```
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project…
Using /usr/local/bin/python3.6m to create virtualenv…
⠋Traceback (most recent call last):
  File "/usr/local/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/usr/local/lib/python2.7/site-packages/pew/__init__.py", line 11, in <module>
    from . import pew
  File "/usr/local/lib/python2.7/site-packages/pew/pew.py", line 42, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/local/lib/python2.7/site-packages/pew/_utils.py", line 22, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 564, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

Virtualenv location:
Warning: Your Pipfile requires python_version 3.6, but you are using None (/bin/python).
  $ pipenv check will surely fail.
Spawning environment shell (/bin/bash). Use 'exit' to leave.
zsmac user ~/Dropbox/sync/dev/fai-calculator/python $ source /bin/activate
bash: /bin/activate: No such file or directory
```

Workaround is to add 

```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
to .bash_profile.

**Comment by martazaryn** [comment]
Thanks @hyperknot !

**Comment by knowsuchagency** [comment]
Make sure you don't have a `setup.cfg` with the following lines in your project's root, or it will cause this issue

    [install]
    prefix=

**Comment by brunokrebs** [comment]
Hey there @kennethreitz, wouldn't it make sense to add a check to see if `LC_ALL` and `LANG` are set?

The `TypeError: 'NoneType' object is not subscriptable` error is not friendly...

If you agree that it would make sense, I can work on a PR. Let me know 😄

**Comment by kennethreitz** [comment]
@brunokrebs i think we already do that, but go for it!

**Comment by cgDeepLearn** [comment]
if you'd installed annaconda and then install pipenv . You could try `conda update python`,and  then `pipenv install`.

(because Anaconda installa
tion changing the system python interpreter path to point to the Anaconda python binary)

---Ubuntu16.04-Anaconda3-python3.6.1-cause this issue

**Comment by brady800526** [comment]
For me, I update the with
`pipenv --update`
then the problem is solved

**Comment by kalinchernev** [comment]
Installing latest version with brew didn't help me today, rather exporting the variables as mentioned earlier. I personally added them in `~/.bash_profile` to persist, not sure whether that's the best with MacOS.

Installed pipenv via pip3 and python3 of brew btw.

**Comment by ms4720** [comment]
this is still broken for plan UTF-8  on OSX 10.12.6 as of today, installed from brew

**Comment by techalchemy** [comment]
@ms4720 en_US.UTF-8

**Comment by rafaelfesi** [comment]
Broken here too.

_SETUP:_

MacOS version: 10.13.4 (High Sierra)

**Python 3**: `brew install python`
**pipenv**: `brew install pipenv`

_SOLUTION:_

Solved by adding the following lines to `~/.bash_profile`:

```bash
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

Then running this command on terminal: `source ~/.bash_profile`

**Comment by yhoiseth** [comment]
If you’re using fish shell:
```
set -gx LANG "en_US.UTF-8"
set -gx LC_ALL "en_US.UTF-8"
```
