### ISSUE TITLE
$ pipenv install not working.

### ISSUE THREAD

**Issue by jeyraof** [kennethreitz/pipenv#83]
```bash
❯ pipenv install
Creating a Pipfile for this project...
Creating a virtualenv for this project...
New python executable in /Users/jeyraof/Work/fashion-keyword/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/jeyraof/Work/fashion-keyword/.venv
No package provided, installing all dependencies.
Pipfile found at /Users/jeyraof/Work/fashion-keyword/Pipfile. Considering this to be the project home.
Installing dependencies from Pipfile...

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 524, in install
    do_init(dev=dev, requirements=requirements, allow_global=system)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 378, in do_init
    click.echo(crayons.yellow('Pipfile.lock not found, creating...', err=True))
TypeError: yellow() got an unexpected keyword argument 'err'

❯
```

When i start up new project, I sent command `$ pipenv install` for initializing default structure.
But no specific pypi-package-name passed, it raised above error.

However, when I pass pypi-package-name on start up, it works well:
`$ pip env install requests`.

how to deal with it ?

Is `$ pipenv install (blank)` bad request?

**Comment by kennethreitz** [comment]
fixed!

**Comment by allisonsnipes** [comment]
Its not fixed I still get the error when I try to run $ pipenv install (blank) its still a bad request.`-bash: pipenv: command not found`

**Comment by kennethreitz** [comment]
@allisonsnipes your issue is unrelated
